# -*- mode:restclinet -*-
#
:base_route = http://localhost:8000/api
#
#
:auth = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InpheWFuIiwiaWF0IjoxNjAzNTI1MjAwLCJleHAiOjE2MDM2MTE2MDB9.z6e29hES5t45H_3RAziRWbaHZRJ1QyhpKc_c2uo8J0w

#

++++++++++++++++++++++++++++++++++++++++++++++++++++
    Auth Routes
++++++++++++++++++++++++++++++++++++++++++++++++++++

# Register
POST :base_route/auth/register
content-type: application/json

{
    "name": "Shahadul Haider",
    "username": "haider",
    "email": "haider@email.com",
    "password": "Hello123"
}

# login
POST :base_route/auth/login
content-type: application/json

{
    "email": "zayan@email.com",
    "password": "Hello123"
}


# Get Current Auth User
GET :base_route/auth/me
Authorization: :auth

content-type: application/json

#
# Verify email
PATCH :base_route/auth/verify?token=cceb7eab-04e8-4a40-ac75-de25b359424b
Authorization: :auth
content-type: application/json

#
# Forgot password
POST :base_route/auth/forgot-password
content-type: application/json

{
    "email": "zayan@email.com"
}

##
# Reset password
PATCH :base_route/auth/reset-password?token=fa514fb2-a77a-4eae-9f08-6da03141dd28
Authorization: :auth
content-type: application/json

{
    "password": "Hello123"
}

#
#
++++++++++++++++++++++++++++++++++++++++++++++++++++
    Users Routes
++++++++++++++++++++++++++++++++++++++++++++++++++++

# Gett All Users
GET :base_route/users

# Get user by id
GET :base_route/users/996c5501-ef0c-4a56-8bad-b431a29d650e

# Get user by username/email
GET :base_route/users/user/jewel
